# A static site
services:
  - type: web
    name: my-blog
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # Enable service previews
    rootDir: my-react-app
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
